module.exports={
  "A menos que":	       "A menos que….jpeg",
  "Alf fichas":          "Alf fichas.jpeg",
  "Amenaza":             "Amenaza.jpeg",
  "Apoyo moción guiño":  "Apoyo la moción con toda violencia (guiño).jpeg",
  "Apoyo moción arma":   "Apoyo la moción con toda violencia (arma).jpeg",
  "asertivo":            "asertivo.jpeg",
  "Atención":            "Atencion.gif",
  "Atómico":             "Atomico.gif",
  "Basura":              "Basura.png",
  "BigBang":             "BigBang.gif",
  "bonjour":             "bonjour.jpeg",
  "bola ingle 1":        "bola ingle 1.jpeg",
  "Burla":               "Burla.mp4",
  "Cama arriba":         "CamaArriba.gif",
  "caras nuevas":        "caras nuevas.jpeg",
  "Cariñito":            "Cariñito.gif",
  "Chester":             "Chester.jpeg",
  "comer una naranja":   "comer una naranja.jpeg",
  "Cómo dice":           "Cómo dice.jpeg",
  "copete":              "copete.png",
  "cruel":               "cruel.jpeg",
  "Cuadrado ordinario":  "CuadradoOrdinario.jpg",
  "Dejen dormir":        "Dejen dormir al prójimo.3gp",
  "Despacio cerebrito":  "MasDespacioCerebrito.jpg",
  "Diabólico":           "Diabolico.jpg",
  "Dije suba":           "Dije suba (cumbancha).png",
  "Distinguir Maramá":   "Distinguir maramá de rombai.jpg",
  "Duelen los bolsillos":"Me duelen los bolsillos.jpeg",
  "enhorabuena de pulgar":"enhorabuena de pulgar.jpeg",
  "Enséñanos a amar":    "Enséñanos a amar.jpeg",
  "Es y no es":          "Es y no es.jpeg",
  "Eso digo yo":         "Eso digo yo.jpeg",
  "Eso me agrada":       "EsoMeAgrada.jpg",
  "Estepicursor":        "Estepicursor.jpeg",
  "Estúpido y sensual":  "EstupidoSensual.gif",
  "Exaaacto":            "Exaaacto.jpeg",
  "Explica tu maqueta":  "Explica tu maqueta.jpeg",
  "Exprimir cada centavo":"Exprimir cada centavo.jpeg",
  "Fernet con Pepsi":    "fernet con pepsi.jpeg",
  "Fuego":               "Fuego.gif",
  "Fuego, y mucho":      "¡Fuego, y mucho!.png",
  "Gazpacho":            "Gazpacho.png",
  "Guiño guiño":         "GuiñoGuiño.gif",
  "Hermoso asador":      "Sí, es un hermoso asador.png",
  "juego perfecto":      "juego perfecto.png",
  "Juramento magio":     "Juramento magio.jpeg",
  "La caja":             "LaCaja.png",
  "leer detenidamente":  "leer detenidamente.jpeg",
  "Lisa insomnio":       "Lisa insomnio.jpeg",
  "Lo rompí":            "Lo rompí.jpeg",
  "Lo sabe todo":        "El maestro lo sabe todo.jpeg",
  "lugar para uno más":  "lugar para uno más.jpeg",
  "Máquina de escribir": "Máquina de escribir invisible.mp4",
  "Máquina invisible":   "MaquinaInvisible.jpg",
  "Mendozaaa":           "Mendozaaa.png",
  "Mi amor es el mar":   "Mi amor es el mar.jpeg",
  "Mi diagnóstico":      "Mi diagnóstico.jpeg",
  "Mi hamburguesa":      "Mi hamburguesa.png",
  "Mi trabajo aquí 1":   "MiTrabajoAqui.jpg",
  "Mi trabajo aquí 2":   "MiTrabajoAqui.gif",
  "misterios":           "Ah, los misterios de la vida.png",
  "Mono tonto":          "MonoEstupido.png",
  "Muere1":              "Muere1.jpg",
  "Muere2":              "Muere2.jpg",
  "Muere3":              "Muere3.jpg",
  "Muere4":              "Muere4.jpg",
  "Muere5":              "Muere5.jpg",
  "muy confuso":         "muy confuso.jpeg",
  "Nada puesto":         "NadaPuesto.gif",
  "Nadie que haya":      "Nadie que haya.jpeg",
  "no es comunista":     "no es comunista.jpeg",
  "No es ilegal":        "NoEsIlegal.jpg",
  "No estaba dormido":   "No estaba dormido, estaba ebrio.jpg",
  "No la dejes ir":      "NoLaDejesIr.png",
  "No lloren por mí":    "No lloren por mí.png",
  "Nube arriba":         "NubeArriba.gif",
  "Oblígame":            "Obligame.jpg",
  "payaso me come":      "payaso me come.jpeg",
  "pensar en los niños": "pensar en los niños.jpeg",
  "Pero es tan barato":  "Pero es tan barato.jpeg",
  "Pipino 2":            "Pipino 2.jpeg",
  "Poderes sexuales":    "PoderesSexuales.jpg",
  "Puede darme dinero":  "PuedeDarmeDinero.jpg",  
  "Pirañas":             "Pirañas.jpg",
  "publicidad fraudulenta":"publicidad fraudulenta.jpeg",
  "Qué clase de hombre": "Qué clase de hombre.jpeg",
  "quémenlo":            "quémenlo.jpeg",
  "que-no-se-puede-romper":"que-no-se-puede-romper.jpeg",
  "Que no toque nada":   "Voy a tocar lo que me dé la gana.jpeg",
  "Que sí Kent":         "QueSiKent.jpg",
  "Quítate tú":          "QuitateTu.gif",  
  "Resultados sexuales": "ResultadosSexuales.jpg",
  "Robar":               "Robar.jpg",
  "Sarcasmo":            "Sarcasmo.gif",
  "ser raza":	           "A veces pareces ser raza.jpeg",
  "Simpson preservativos":"Simpson preservativos.jpeg",
  "spoiler":             "spoiler.jpeg",
  "su silencio lo incrimina":"su silencio lo incrimina.jpeg",
  "SUBE bien cargada":   "SUBE bien cargada.jpeg",
  "Tabla":               "Tabla.gif",
  "Tan temprano":        "Qué, tan temprano.jpeg",
  "Te entiendo":         "Ah, te entiendo mi viejo.jpeg",
  "Toalla":              "Toalla.jpg",
  "Todavía sirve":       "TodaviaSirve.jpg",
  "Trabajamos":          "Trabajamos.gif",
  "Travestis":           "Esas hermosas mujeres.jpeg",
  "Triunfador":          "Triunfador.jpg",
  "Tu ortografía mató":  "Tu ortografía mató a Linguo.jpeg",
  "Un poco de esto":     "Un poco de esto, un poco de aquello.jpeg",
  "Vela perfumada":      "Vela perfumada.png",
  "Venga el líquido":    "Venga el líquido.jpeg",
  "Vengan":              "Vengan.gif",
  "viejos fumados":      "viejos fumados.jpeg",
  "Vivo para dar":       "Vivo para dar.jpeg",
  "Volver al futuro":    "VolverFuturo.jpg",
  "Y ahí fue cuando me enojé":"Y ahí fue cuando me enojé.png",
  "Y me refiero ahí abajo":"Y me refiero ahí abajo.jpeg",
  "Y si era tan listo":  "Y si era tan listo.jpeg",
  "Yo quería maní":      "Yo quería maní.jpeg",
  "Ya se ha visto":      "YaSeHaVisto.jpg",
  "Yo estoy más":        "Yo estoy más polvoso que vos.jpeg",
  "Yo no entendí":       "Yo no entendí la película.jpeg",
 };