module.exports={
  "Atención":               "BQADAQADGwADK-F4DkONNYB5afQ7Ag",
  "Basura":                 "AgADAQADC6gxGyvheA4FyDkRCiTiBWyr5y8ABAZJZPNPyWGoll8BAAEC",
  "Burla":                  "BQADAQADjwEAAt3laAasnDcuu4HyVAI",
  "Cama arriba":            "BQADAQADGAADK-F4DqI6bSG50lmPAg",
  "Cariñito":               "BQADAQADHgADK-F4DnTvXGAdWPCYAg",
  //"Cómo dice":              "",
  "Cuadrado ordinario":     "AgADAQADvacxGyvheA7FbVi_p8yvXkHv5y8ABDyEG1tG07kOTa0AAgI",
  "Fuego":                  "BQADAQADGQADK-F4DuYTfXgKYEnRAg",
  "La caja":                "AgADAQADkbUxGw9iNQkblGoVXJyFzaCa5y8ABEKZRSfrYBSDYjwBAAEC",
  "Máquina de escribir":    "BAADAQADLgADK-F4DjlBc0x9BmtAAg",
  "Máquina invisible":      "AgADAQADxqgxGyvheA5hpbesAbiKCXyU5y8ABA6r_4rcctB-LaQBAAEC",
  "Muere1":                 "AgADAQAD9acxGyvheA433ok4PmGD2CGU5y8ABAuQMjRBS4Q9YmABAAEC",
  "Muere2":                 "AgADAQAD-6cxGyvheA7depgc_1-3JFOL5y8ABNOBZnZ-8HtTHl0BAAEC",
  "Muere3":                 "AgADAQADCagxGyvheA7REbxjkCJY2izB5y8ABNukD8AgZwABTV5gAQABAg",
  "Muere4":                 "AgADAQAD86cxGyvheA7zq1IyXRZEAAHfwOcvAAReoPJZs01-RbpdAQABAg",
  "Muere5":                 "AgADAQAD8qcxGyvheA6x6FijocKkwcfG5y8ABIIRI54wf9IJGGIBAAEC",
  "Muy mucho":              "AgADAQADrKcxG8OJ1xFMBJiBRBsyM32p5y8ABMHNJCcB8_nnlGkBAAEC",
  "No es ilegal":           "AgADAQADv6cxGyvheA5ueT-s7Abcpcu75y8ABNA_wc94es6kiz0BAAEC",
  "Nube arriba":            "BQADAQADFwADK-F4DrMBNENgFmyHAg",
  "Oblígame":               "AgADAQADu6cxGyvheA5xXHrio85B_ziS5y8ABBdWprdfKS8tWToBAAEC",
  "Puede darme dinero":     "AgADAQADvqcxGyvheA7e35lBXW8aZsqu5y8ABEfYbwzIUTaJ3joBAAEC",
  "Que sí Kent":            "AgADAQADCqgxGyvheA7hZbWPI4xChVf05y8ABOgdVrMMFl1I2M0AAgI",
  "Quítate tú":             "BQADAQADHAADK-F4DpmI_YBLi48pAg",
  "Te entiendo":            "AgADAQADD6gxGyvheA6BPc2aESUMpZ2o5y8ABGqSVxs8Al59H3oBAAEC",
  "Trabajamos":             "BQADAQADGgADK-F4DqAPMUTYHBRCAg",
  "Toalla":                 "AgADAQADuacxGyvheA6zdpzynsfcUueo5y8ABBnM6mUKNgUXuDoBAAEC",
  "Vela perfumada":         "AgADAQAD8acxGyvheA46jTqy70xLuInA5y8ABF0W2VnVDfYoMm",
  "Volver al futuro":       "AgADAQADvKcxGyvheA6iidI-dVExnYi85y8ABIiAMvW2CvPQ8TsBAAEC",
 };